web:
  hosts:
    ubuntu-1:
      ansible_host: 3.70.208.222
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ubuntu-2:
      ansible_host: 3.71.33.179
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
main:
  hosts:
    main-ubuntu:
      ansible_host: 3.69.174.13
      ansible_user: ubuntu
      ansible_password: 12345
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
