---
- name: Wordpress Installation & Configuration
  hosts: all
  become: yes
  vars_files: vars.yml

  tasks:
    - name: Install Pip Module 
      apt: 
        name: python3-pip

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Deploy MariaDB server
      docker_container:
        image: mariadb
        name: mariadb
        volumes: 
          - "{{ db_volume }}:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: "{{ root_password }}"
          MYSQL_PASSWORD: "{{ root_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"
    - name: Deploy Wordpress
      docker_container:
        image: wordpress
        name: Wordpress
        restart_policy: always
        ports: 
          - "8080:80"
        links: "{{ db_volume }}:/var/lib/mysql"
        volumes:
            - "{{wordpress}}:/var/www/html"
        env:
          MYSQL_ROOT_PASSWORD: "{{ root_password }}"
          MYSQL_PASSWORD: "{{ root_password }}"
          MYSQL_DATABASE: "{{ db_name }}"
          MYSQL_USER: "{{ db_user }}"